### ISSUE TITLE
Create a report in README file

### ISSUE THREAD

**Issue by Alina-Khindanova** [Alina-Khindanova/ECO395M_final_project#12]

**Comment by yzliu123** [comment]
Hi @Alina-Khindanova could you provide a frame of readme file? I can help with my table related part.

**Comment by Alina-Khindanova** [comment]
> oh
> 
> > Hi @Alina-Khindanova could you provide a frame of readme file? I can help with my table related part.
> 
> Oh, sorry, I saw it. I copy it to our google doc so we can make any changes there. https://docs.google.com/document/d/1Lm_6_O2VZS9RLM-S-MMhsxI0-PqbAAI25ygm_9Opi5I/edit?usp=sharing

Thank you for your help!
